name: heart-disease-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - pandas
    - numpy
    - scikit-learn
    - mlflow
    - dagshub
    - matplotlib
    - seaborn
