- name: Run MLflow Project
        id: mlflow_run
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/zulfiana92/Eksperimen_SML_Zulfiana-Majid.mlflow
        run: |
          cd MLProject
          python modelling.py
          RUN_ID=$(python -c "
          import mlflow
          import os
          os.environ['MLFLOW_TRACKING_URI'] = 'https://dagshub.com/zulfiana92/Eksperimen_SML_Zulfiana-Majid.mlflow'
          client = mlflow.tracking.MlflowClient()
          runs = client.search_runs('2', order_by=['start_time DESC'], max_results=1)
          print(runs[0].info.run_id)
          ")
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Build Docker Image with MLflow
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/zulfiana92/Eksperimen_SML_Zulfiana-Majid.mlflow
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow models build-docker \
            --model-uri "runs:/${{ steps.mlflow_run.outputs.run_id }}/random_forest_model" \
            --name "${{ secrets.DOCKERHUB_USERNAME }}/heart-disease-model:latest"